### ISSUE TITLE
P2P Demo problem

### ISSUE THREAD

**Issue by maxcorrads** [w3c/web-of-things-framework#76]
Hello I was trying the P2P demo but it say:
`error: uncaughtException: Cannot find module '../../../libs/message/wotmsg' date=Tue Nov 22 2016 13:54:14 GMT+0100 (CET), pid=36005, uid=501, gid=20, cwd=/Users/user/Desktop/web-of-things-framework/examples/p2p_demo, execPath=/usr/local/bin/node, version=v6.9.1, argv=[/usr/local/bin/node, /Users/user/Desktop/web-of-things-framework/examples/p2p_demo/demo.js], rss=44527616, heapTotal=23744512, heapUsed=13480936, loadavg=[1.625, 1.73095703125, 1.8681640625], uptime=494009, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=469, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=417, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=497, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=14, file=/Users/user/Desktop/web-of-things-framework/libs/transport/p2p/wotkad/lib/node.js, function=, line=40, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=579, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=438, method=Module._load, native=false], stack=[Error: Cannot find module '../../../libs/message/wotmsg',     at Function.Module._resolveFilename (module.js:469:15),     at Function.Module._load (module.js:417:25),     at Module.require (module.js:497:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/Users/user/Desktop/web-of-things-framework/libs/transport/p2p/wotkad/lib/node.js:40:14),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3)]
`

**Comment by zsoltpardi** [comment]
I will test the solution and let you know what is the problem. Based on the error message I assume the path is incorrect for the wotmsg module. Perhaps it should be '../../libs/message/wotmsg' instead of '../../../libs/message/wotmsg', but I will try to test it and check in the correct code.

**Comment by maxcorrads** [comment]
Thank you for your answer, if I change it to (file web-of-things-framework/libs/transport/p2p/wotkad/lib/node.js)
`var wotmsg = require('../../../../../libs/message/wotmsg');`
 which should be the correct path I get: 

```
debug: Initialising framework
debug: p2p server configuration exists. Start p2p server
error: P2P handler start error {"name":"AssertionError","expected":true,"operator":"==","message":"No log adapter supplied","generatedMessage":false}
debug: WoT Framework transport is initialised
debug: creating Thing: Toyota
info: Bootstrap P2P network, initiate seed node
debug: starting Toyota
error: Error in initialising thing: No log adapter supplied
debug: creating Thing: Ford
debug: starting Ford
error: Error in initialising thing: No log adapter supplied
debug: WoT Framework things are initialised
debug: Start device simulator to communicate with WoT via a P2P network
debug: starting P2P device simulator for Toyota
error: Error in initialising framework No log adapter supplied
```

**Comment by zsoltpardi** [comment]
The underlying kademlia DHT library expects a logger be passed and it seems there is an incorrect logger object is passed. I need to review the whole source of this. This was created  a long time ago as an experimental design and it seems the whole implementation requires a review. Other issue with this design, such P2P network requires seed nodes as well, it won't work without seeds, but there are no operational seeds. I suggest try Streembit at https://github.com/streembit/streembit-pi which has active seeds, it is a kademlia based P2P Raspberry Pi  design and it tries to implement W3C WoT. Since it is not operational I will most likely remove this P2P implementation from here.
